#!/usr/bin/env bash
# This script display the content of a directory in a list format

for file in *; do
  if [[ -f "$file" && ! "$file" == .* ]]; then
    filename=$(echo "$file" | cut -d '-' -f2-)
    echo "$filename"
  fi
done
