#!/usr/bin/env bash
#Power of Love
pid_file="/var/run/myscript.pid"

# Function to handle SIGTERM signal
handle_sigterm() {
trap "echo 'I hate the kill command'" SIGTERM
}

# Function to handle SIGINT signal
handle_sigint() {
    echo "Y U no love me?!"
}

# Function to handle SIGQUIT and SIGTERM signals
handle_sigquit() {
    rm "$pid_file"  # Delete the PID file
    exit 0  # Terminate the script
}

# Trap signals and assign corresponding functions
trap handle_sigterm SIGTERM
trap handle_sigint SIGINT
trap handle_sigquit SIGQUIT SIGTERM

# Create PID file
echo "$$" > "$pid_file"

# Display "To infinity and beyond" indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 1
done

